version: "3.8"
services:
  mongodb:
    image: "mongo:latest"
    restart: "unless-stopped"
    volumes:
      - 'mongodb_data_container:/data/db'
    environment:
      - "MONGO_INITDB_DATABASE=myDatabase"
      - "MONGO_INITDB_ROOT_PASSWORD=secret"
      - "MONGO_INITDB_ROOT_USERNAME=root"
    ports:
      - "27017:27017"
volumes:
  mongodb_data_container: